version: '3.8'

services:
  app:
    build: .
    ports:
      - "9120:9120"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/gambling?currentSchema=gamble
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 19031988
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: gambling
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 19031988
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
